from __future__ import annotations

PACKAGE_EXTENSION = ".nova-plugin"
PACKAGE_MANIFEST_FILENAME = "package.json"
PLUGIN_MANIFEST_FILENAME = "manifest.json"
PACKAGE_FORMAT_VERSION = "1.0"
SUPPORTED_PACKAGE_FORMATS: frozenset[str] = frozenset({PACKAGE_FORMAT_VERSION})

ENV_PLUGIN_INSTALL_DIR = "NOVA_PLUGIN_INSTALL_DIR"
DEFAULT_INSTALL_DIRNAME = "plugins"
DEFAULT_INSTALLED_SUBDIR = "installed"
