import {
  Callout,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text,
} from "cursor/canvas";

export default function ReleaseEngSprint2Artifacts() {
  return (
    <Stack gap={24} style={{ padding: 24, maxWidth: 1100 }}>
      <Stack gap={8}>
        <H1>Release Engineering Sprint 2</H1>
        <Text tone="secondary">
          Focus: Release Artifact generation · Audit only · No CI · No app changes · 2026-07-30
        </Text>
        <Row gap={8} style={{ flexWrap: "wrap" }}>
          <Pill tone="success">Wheel: tooling OK</Pill>
          <Pill tone="deleted">sdist: missing</Pill>
          <Pill tone="warning">SHA: embedded only</Pill>
          <Pill tone="success">Seal: implemented</Pill>
        </Row>
      </Stack>

      <Callout tone="warning" title="Artifact generation status">
        Manual pipeline can produce and seal a wheel + reports. Source distribution (sdist) and a
        standalone checksum manifest required by 23_RELEASE_CI are not generated by current seal
        tooling. Latest sealed candidate remains 0.1.4 — no 1.0.0rc1 artifacts yet.
      </Callout>

      <Grid columns={4} gap={12}>
        <Stat value="OK" label="Wheel path" tone="success" />
        <Stat value="NO" label="sdist path" tone="danger" />
        <Stat value="OK*" label="SHA256 in reports" tone="warning" />
        <Stat value="OK" label="Seal + manifest" tone="success" />
      </Grid>

      <Divider />

      <H2>Pipeline (manual)</H2>
      <Text size="small">
        quality gate → pip wheel → nova-release-verify → nova-install-smoke → nova-acceptance →
        nova-release-candidate → nova-release-audit
      </Text>

      <H2>Missing vs Integrity / CI policy</H2>
      <Table
        headers={["Artifact", "Status"]}
        rows={[
          ["Wheel", "Present (legacy 0.1.x; not rc1)"],
          ["sdist", "Missing — not in Process or seal"],
          ["Standalone SHA256SUMS", "Missing — checksums only inside JSON/manifest"],
          ["release_manifest.json", "Generated by seal tool"],
          ["CI Report", "Out of Sprint 2 / CI sprint"],
          ["git identity in seal", "Missing (Sprint 1 gap)"],
        ]}
        rowTone={["success", "danger", "warning", "success", "neutral", "warning"]}
      />
    </Stack>
  );
}
